################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Components/simpliciti/nwk_applications/nwk_freq.obj: ../Components/simpliciti/nwk_applications/nwk_freq.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\Access Point\smpl_config_AP.dat"  -vmsp --use_hw_mpy=none --include_path="C:/ti/ccsv7/ccs_base/msp430/include" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/boards/EZ430RF" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/drivers" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/mrfi" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk_applications" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/utils" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --advice:power="all" --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="Components/simpliciti/nwk_applications/nwk_freq.d" --obj_directory="Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/nwk_applications/nwk_ioctl.obj: ../Components/simpliciti/nwk_applications/nwk_ioctl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\Access Point\smpl_config_AP.dat"  -vmsp --use_hw_mpy=none --include_path="C:/ti/ccsv7/ccs_base/msp430/include" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/boards/EZ430RF" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/drivers" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/mrfi" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk_applications" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/utils" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --advice:power="all" --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="Components/simpliciti/nwk_applications/nwk_ioctl.d" --obj_directory="Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/nwk_applications/nwk_join.obj: ../Components/simpliciti/nwk_applications/nwk_join.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\Access Point\smpl_config_AP.dat"  -vmsp --use_hw_mpy=none --include_path="C:/ti/ccsv7/ccs_base/msp430/include" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/boards/EZ430RF" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/drivers" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/mrfi" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk_applications" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/utils" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --advice:power="all" --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="Components/simpliciti/nwk_applications/nwk_join.d" --obj_directory="Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/nwk_applications/nwk_link.obj: ../Components/simpliciti/nwk_applications/nwk_link.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\Access Point\smpl_config_AP.dat"  -vmsp --use_hw_mpy=none --include_path="C:/ti/ccsv7/ccs_base/msp430/include" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/boards/EZ430RF" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/drivers" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/mrfi" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk_applications" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/utils" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --advice:power="all" --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="Components/simpliciti/nwk_applications/nwk_link.d" --obj_directory="Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/nwk_applications/nwk_mgmt.obj: ../Components/simpliciti/nwk_applications/nwk_mgmt.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\Access Point\smpl_config_AP.dat"  -vmsp --use_hw_mpy=none --include_path="C:/ti/ccsv7/ccs_base/msp430/include" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/boards/EZ430RF" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/drivers" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/mrfi" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk_applications" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/utils" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --advice:power="all" --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="Components/simpliciti/nwk_applications/nwk_mgmt.d" --obj_directory="Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/nwk_applications/nwk_ping.obj: ../Components/simpliciti/nwk_applications/nwk_ping.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\Access Point\smpl_config_AP.dat"  -vmsp --use_hw_mpy=none --include_path="C:/ti/ccsv7/ccs_base/msp430/include" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/boards/EZ430RF" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/drivers" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/mrfi" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk_applications" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/utils" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --advice:power="all" --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="Components/simpliciti/nwk_applications/nwk_ping.d" --obj_directory="Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Components/simpliciti/nwk_applications/nwk_security.obj: ../Components/simpliciti/nwk_applications/nwk_security.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\milesdai\Documents\tempData\MIT\UROP\cubebots\Application\configuration\Access Point\smpl_config_AP.dat"  -vmsp --use_hw_mpy=none --include_path="C:/ti/ccsv7/ccs_base/msp430/include" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/boards/EZ430RF" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/bsp/drivers" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/mrfi" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/Components/simpliciti/nwk_applications" --include_path="C:/Users/milesdai/Documents/tempData/MIT/UROP/cubebots/utils" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --advice:power="all" --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="Components/simpliciti/nwk_applications/nwk_security.d" --obj_directory="Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


